server:
  port: 8081

spring:
  application:
    name: ingest-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html